#!/bin/sh

REL="$(dirname "$0")"

WRL="$REL/world"
JIRI="$REL/jiri"
JAZZ="$REL/jazz"
JAZ="$JAZZ/jaz"

UPDATE_SUBMODULES="true"

bootstrap_init () {
    cd "$REL"
    git submodule init
}

bootstrap_update () {
    cd "$REL"
    git submodule update
}

bootstrap () {
    (bootstrap_init) &&
    (bootstrap_update)
}

bootstrap_dispatch () {
    case "$1" in
	"init" )
	    bootstrap_init
	    ;;
	"update" )
	    bootstrap_update
	    ;;
	"" )
	    bootstrap
	    ;;
	* )
	    echo "Unknown bootstrap option : $1"
	    return 1
	    ;;
    esac
}

display_info () {
    echo "$1"
    if [ -d "$2" ]; then
	     cd "$2" &&
	     git log -1
    fi
}

display_all_info () {
    (display_info "Together" "$REL")
    echo
    (display_info "World" "$WRL")
    echo
    (display_info "Jiri" "$JIRI")
    echo
    (display_info "Jazz" "$JAZZ")
}

display_status () {
    echo "$1"
    if [ -d "$2" ]; then
	     cd "$2" &&
	     git status
    fi
}

display_all_status () {
    (display_status "Together" "$REL")
    echo
    (display_status "World" "$WRL")
    echo
    (display_status "Jiri" "$JIRI")
    echo
    (display_status "Jazz" "$JAZZ")
}

pull () {
    echo "$1"
    if [ -d "$2" ]; then
	     cd "$2" &&
	     git pull
    fi
}

pull_all () {
    (pull "Together" "$REL")
    echo
    (pull "World" "$WRL")
    echo
    (pull "Jiri" "$JIRI")
    echo
    (pull "Jazz" "$JAZZ")
}

update_submodules () {
    cd "$REL"
    git submodule update --recursive
}

while getopts "lr" OPTION; do
    case $OPTION in
	"l" )
	    UPDATE_SUBMODULES="false"
	    ;;
	"r" )
	    UPDATE_SUBMODULES="true"
	    ;;
    esac
done

shift $((OPTIND-1))

case "$1" in
	"bootstrap" )
		bootstrap_dispatch $2
		exit
		;;

	"info" )
		display_all_info
		exit
		;;

	"status" )
		display_all_status
		exit
		;;

	"pull" )
		pull_all
		exit
		;;
esac

if [ ! -f "$JAZ" ]; then
	bootstrap
elif $UPDATE_SUBMODULES; then
    (update_submodules)
fi

if [ ! -f "$JAZ" ]; then
	echo "Unable to find jazz/jaz"
	exit 1
fi

exec "$JAZ" "$@"
