#! /bin/sh

TOGETHER=~/Devel/together
INSTALL=$TOGETHER/install
NOTARY=$TOGETHER/notary

if [ -f ".jaz" ]; then
  . "$(pwd)/.jaz"
else
  echo ".jaz not found"
  exit 1
fi

if [ -z "$JAZCONF" ]; then
  echo "JAZCONF not set"
  exit 1
else
  ENVIRONMENT="$JAZCONF"
fi

if [[ "$(arch)" == "arm64" ]]; then
  APP=together-$ENVIRONMENT-silicon
else
  APP=together-$ENVIRONMENT-mac
fi

# Bail out
set -e

# Notarize
cd $NOTARY
ditto -c -k --keepParent $APP.app $APP.zip
xcrun notarytool submit $APP.zip --apple-id gucartier@gmail.com --team-id R74FF3EJWG --keychain-profile Together --verbose --wait
xcrun stapler staple -v $APP.app

# Notes
# - if the notarization fails, there will be a LogFileURL that can be pasted into a browser to have a full log
