#! /bin/sh

TOGETHER=~/Devel/together
INSTALL=$TOGETHER/install
NOTARY=$TOGETHER/notary

if [ -f ".jaz" ]; then
  . "$(pwd)/.jaz"
else
  echo ".jaz not found"
  exit 1
fi

if [ -z "$JAZCONF" ]; then
  echo "JAZCONF not set"
  exit 1
else
  ENVIRONMENT="$JAZCONF"
fi

if [[ "$(arch)" == "arm64" ]]; then
  APP=together-$ENVIRONMENT-silicon
else
  APP=together-$ENVIRONMENT-mac
fi

# Bail out
set -e

# Notarize
cd $NOTARY
/usr/bin/ditto -c -k --keepParent $APP.app $APP.zip
/usr/bin/xcrun altool --notarize-app -f $APP.zip --primary-bundle-id com.togethersphere.Together -u gucartier@gmail.com -p @keychain:Together --output-format xml

echo rm $NOTARY/$APP.zip
echo /usr/bin/xcrun altool --notarization-info key-returned-from-previous-command -u gucartier@gmail.com -p @keychain:Together
echo /usr/bin/xcrun stapler staple -v $NOTARY/$APP.app

# Notes
# - if the notarization fails, there will be a LogFileURL that can be pasted into a browser to have a full log
