#! /bin/sh

./package-pre
./package-post

# Test
# Mount dmg and check that it worked
# Unmount it

# delete $NOTARY/$APP.app so that there is no url types
# Info.plist active

# Push
# Copy $TOGETHER_DMG to website/limited
# commit and push
# go to montreal
# cd /var/www/together
# sudo git pull
