#! /bin/sh

TOGETHER=~/Devel/together
NOTARY=$TOGETHER/notary
PACKAGE=$TOGETHER/package
MOUNT="/Volumes/Together"

if [[ "$(arch)" == "arm64" ]]; then
  APP="together-prod-silicon"
  TEMPLATE_DMG="TogetherTemplateSilicon.dmg"
  TOGETHER_DMG="Together Apple Silicon.dmg"
else
  APP="together-prod-mac"
  TEMPLATE_DMG="TogetherTemplate.dmg"
  TOGETHER_DMG="Together.dmg"
fi

# Bail out
set -e

cd $PACKAGE

# Copy files
# cp -R $NOTARY/$APP.app $MOUNT/Together.app
cp -R background $MOUNT/.background
ln -s /Applications $MOUNT/Applications

# Prettify
/usr/bin/osascript Prettify

# Detach and compress
hdiutil detach -quiet $MOUNT
hdiutil convert "$TEMPLATE_DMG" -quiet -format UDZO -o "$TOGETHER_DMG"
rm "$TEMPLATE_DMG"
