#! /bin/sh

TOGETHER=~/Devel/together
NOTARY=$TOGETHER/notary
PACKAGE=$TOGETHER/package
MOUNT="/Volumes/Together"

if [ -f ".jaz" ]; then
  . "$(pwd)/.jaz"
else
  echo ".jaz not found"
  exit 1
fi

if [ -z "$JAZCONF" ]; then
  echo "JAZCONF not set"
  exit 1
else
  ENVIRONMENT="$JAZCONF"
fi

if [[ "$ENVIRONMENT" == "prod" ]]; then
  SUFFIX=""
else
  SUFFIX=" Test"
fi

if [[ "$(arch)" == "arm64" ]]; then
  APP="together-$ENVIRONMENT-silicon"
  TEMPLATE_DMG="TogetherTemplateSilicon.dmg"
  TOGETHER_DMG="Together$SUFFIX Apple Silicon.dmg"
else
  APP="together-$ENVIRONMENT-mac"
  TEMPLATE_DMG="TogetherTemplate.dmg"
  TOGETHER_DMG="Together$SUFFIX.dmg"
fi

# Bail out
set -e

cd $PACKAGE

# Copy files
# cp -R $NOTARY/$APP.app $MOUNT/Together.app
cp -R background $MOUNT/.background
ln -s /Applications $MOUNT/Applications

# Prettify
/usr/bin/osascript "Prettify$SUFFIX"

# Detach and compress
hdiutil detach -quiet $MOUNT
hdiutil convert "$TEMPLATE_DMG" -quiet -format UDZO -o "$TOGETHER_DMG"
rm "$TEMPLATE_DMG"
