#! /bin/sh

TOGETHER=~/Devel/together
NOTARY=$TOGETHER/notary
PACKAGE=$TOGETHER/package
MOUNT="/Volumes/Together"

if [ -f ".jaz" ]; then
  . "$(pwd)/.jaz"
else
  echo ".jaz not found"
  exit 1
fi

if [ -z "$JAZCONF" ]; then
  echo "JAZCONF not set"
  exit 1
else
  ENVIRONMENT="$JAZCONF"
fi

if [[ "$ENVIRONMENT" == "prod" ]]; then
  SUFFIX=""
else
  SUFFIX=" Test"
fi

if [[ "$(arch)" == "arm64" ]]; then
  APP="together-$ENVIRONMENT-silicon"
  TEMPLATE_DMG="TogetherTemplateSilicon.dmg"
  TOGETHER_DMG="Together$SUFFIX Apple Silicon.dmg"
else
  APP="together-$ENVIRONMENT-mac"
  TEMPLATE_DMG="TogetherTemplate.dmg"
  TOGETHER_DMG="Together$SUFFIX.dmg"
fi

# Bail out
set -e

cd $PACKAGE

# Setup
if [ -d "$MOUNT" ]; then
	hdiutil detach -quiet "$MOUNT"
fi

if [ -f "$TEMPLATE_DMG" ]; then
	rm "$TEMPLATE_DMG"
fi

if [ -f "$TOGETHER_DMG" ]; then
	rm "$TOGETHER_DMG"
fi

# Create and attach template
hdiutil create -quiet -volname Together -fs HFS+ -size 400m -attach "$TEMPLATE_DMG"

# Copy files
cp -R "$NOTARY/$APP.app" "$MOUNT/Together$SUFFIX.app"
