#! /bin/sh

if [ -f ".jaz" ]; then
  . "$(pwd)/.jaz"
else
  echo ".jaz not found"
  exit 1
fi

if [ -z "$JAZCONF" ]; then
  echo "JAZCONF not set"
  exit 1
else
  ENVIRONMENT="$JAZCONF"
fi

if [[ "$ENVIRONMENT" == "prod" ]]; then
  SUFFIX=""
else
  SUFFIX=" Test"
fi

case "$(uname -s)" in
  Linux* )
      PLATFORM=linux
      ;;
  Darwin* )
      TOGETHER=~/Devel/together
      PACKAGE=$TOGETHER/package
      WEBSITE=$TOGETHER/website
      if [[ "$(arch)" == "arm64" ]]; then
        PLATFORM=silicon
      elif [[ "$(arch)" == "i386" ]]; then
        PLATFORM=mac
      else
        PLATFORM=unknown
      fi
      ;;
  MINGW* )
      TOGETHER=/c/Home/together
      SETUP=$TOGETHER/setup
      WEBSITE=$TOGETHER/website
      PLATFORM=windows
      ;;
  * )
      PLATFORM=unknown
      ;;
esac

case "$PLATFORM" in
  "mac" )
      cd "$WEBSITE/limited/mac"
      cp "$PACKAGE/Together$SUFFIX.dmg" .
      jas sync
      jas upload
      ;;
  "silicon" )
      cd "$WEBSITE/limited/silicon"
      cp "$PACKAGE/Together$SUFFIX Apple Silicon.dmg" .
      jas sync
      jas upload
      ;;
  "windows" )
      cd "$WEBSITE/limited/windows"
      cp "$SETUP/Together$SUFFIX Setup.exe" .
      jas sync
      jas upload
      ;;
  * )
      echo "Unknown platform $PLATFORM"
      ;;
esac
