#! /bin/sh

if [ -f ".jaz" ]; then
    . "$(pwd)/.jaz"
fi

GSTREAMER=/Library/Frameworks/GStreamer.framework/Versions/1.0
LIB=jazz/lib/jazz.stream/foreign/mac/gstreamer/gstreamer
DEST=$JAZDEST/Libraries/gstreamer

relocate() {
    $JAZDEST/jazz -run relocate file $1 $2 /Library/Frameworks/GStreamer.framework/Versions/1.0 @rpath/gstreamer
}

cpplugin() {
    cp $GSTREAMER/$1 $LIB/$1
    relocate $LIB $1
    cp $LIB/$1 $DEST/$1
}

cpshared() {
    cp $GSTREAMER/$1 $LIB/$1
    relocate $LIB $1
    cp $LIB/$1 $DEST/$1
}

#cpplugin lib/gstreamer-1.0/libgstaudiorate.dylib
#cpplugin lib/gstreamer-1.0/libgstwavenc.dylib
#cpplugin lib/gstreamer-1.0/libgstrsvg.dylib
#cpplugin lib/gstreamer-1.0/libgstwebrtcdsp.dylib

#cpshared lib/libgstbadaudio-1.0.0.dylib
#cpshared lib/libwebrtc_audio_processing.0.dylib
