#! /bin/sh

if [ -f ".jaz" ]; then
    . "$(pwd)/.jaz"
fi

RNNOISE=/Users/cartier/Devel/gstreamer/rnnoise
LIBNAME=libgstrnnoise.dylib
DEST=$JAZDEST/Libraries/gstreamer/lib/gstreamer-1.0

relocate() {
    $JAZDEST/jazz -run relocate file $1 $2 /Library/Frameworks/GStreamer.framework/Versions/1.0 @rpath/gstreamer
}

cp $RNNOISE/build/plugin/$LIBNAME $DEST/$LIBNAME
relocate $DEST $LIBNAME
