#! /bin/sh

LIBNAME=libwebrtc.dylib
WEBRTC=/Users/cartier/Devel/gstreamer/webrtc/build
DEST=cache/develop/Libraries/gstreamer/lib
STREAM=jazz/lib/jazz.stream/foreign/mac/gstreamer

cp $WEBRTC/$LIBNAME $DEST/$LIBNAME
cp $DEST/$LIBNAME $STREAM/gstreamer/lib/$LIBNAME
