#! /bin/sh

if [ -f ".jaz" ]; then
    . "$(pwd)/.jaz"
fi

GSTREAMER=/Library/Frameworks/GStreamer.framework/Versions/1.0
LIB=jazz/foreign/jazz.stream/silicon/gstreamer
DEST=$JAZDEST/Libraries/gstreamer

relocate() {
    $JAZDEST/jazz -run relocate file $1 $2 /Library/Frameworks/GStreamer.framework/Versions/1.0 @rpath/gstreamer
}

cpplugin() {
    cp $GSTREAMER/$1 $LIB/$1
    relocate $LIB $1
    cp $LIB/$1 $DEST/$1
}

cpshared() {
    cp $GSTREAMER/$1 $LIB/$1
    relocate $LIB $1
    cp $LIB/$1 $DEST/$1
}

cpplugin lib/gstreamer-1.0/libgstflv.dylib
cpplugin lib/gstreamer-1.0/libgstrtmp.dylib

cpshared lib/libcrypto.1.1.dylib
cpshared lib/libssl.1.1.dylib
cpshared lib/librtmp.1.dylib
