#! /bin/sh

LIBNAME=libwebrtc.dylib
WEBRTC=/Users/cartier/Devel/gstreamer/webrtc/build
STREAM=jazz/lib/jazz.stream/foreign/mac/gstreamer
DEST=cache/develop/Libraries/gstreamer/lib

cp $WEBRTC/$LIBNAME $STREAM/gstreamer/lib/$LIBNAME
cp $WEBRTC/$LIBNAME $DEST/$LIBNAME
