#! /bin/sh

./prepare

TOGETHER=~/Devel/together
INSTALL=$TOGETHER/install
NOTARY=$TOGETHER/notary

if [ -f ".jaz" ]; then
  . "$(pwd)/.jaz"
else
  echo ".jaz not found"
  exit 1
fi

if [ -z "$JAZCONF" ]; then
  echo "JAZCONF not set"
  exit 1
else
  ENVIRONMENT="$JAZCONF"
fi

if [[ "$(arch)" == "arm64" ]]; then
  APP=together-$ENVIRONMENT-silicon
else
  APP=together-$ENVIRONMENT-mac
fi

if [[ "$(arch)" == "arm64" ]]; then
  BUILD=$TOGETHER/app/$ENVIRONMENT/binaries/$ENVIRONMENT/Libraries/lib
else
  BUILD=$TOGETHER/app/$ENVIRONMENT-x86/binaries/$ENVIRONMENT/Libraries/lib
fi

# Bail out
set -e

# Setup
echo Copying...
cd $NOTARY
rm -rf $APP.app
mkdir $APP.app
cd $APP.app
mkdir Contents
cp $INSTALL/$APP/Contents/Info.plist Contents
cp -r $INSTALL/$APP/Contents/MacOS Contents
cp -r $INSTALL/$APP/Contents/_CodeSignature Contents
mkdir Contents/Resources
cp $INSTALL/$APP/Contents/Resources/together.icns Contents/Resources
cp -r $INSTALL/$APP/Contents/Resources/lib Contents/Resources
mkdir Contents/Libraries
cp $INSTALL/$APP/Contents/Libraries/libcairo.2.dylib Contents/Libraries
cp $INSTALL/$APP/Contents/Libraries/libcrypto.1.1.dylib Contents/Libraries
cp $INSTALL/$APP/Contents/Libraries/libfontconfig.1.dylib Contents/Libraries
cp $INSTALL/$APP/Contents/Libraries/libfreetype.6.dylib Contents/Libraries
cp $INSTALL/$APP/Contents/Libraries/libpixman-1.0.dylib Contents/Libraries
cp $INSTALL/$APP/Contents/Libraries/libpng16.16.dylib Contents/Libraries
cp $INSTALL/$APP/Contents/Libraries/libssl.1.1.dylib Contents/Libraries
mkdir Contents/Libraries/lib
copylib() {
    mkdir Contents/Libraries/lib/$1
    cp $BUILD/$1/.package Contents/Libraries/lib/$1
    cp $BUILD/$1/$1.l1 Contents/Libraries/lib/$1
}
copylib foundation
copylib gambit
copylib contrib.irregex
copylib jazz
copylib jazz.appl
copylib jazz.associative
copylib jazz.cairo
copylib jazz.fontconfig
copylib jazz.foreign
copylib jazz.freetype
copylib jazz.inspector
copylib jazz.io
copylib jazz.math
copylib jazz.moment
copylib jazz.product
copylib jazz.settings
copylib jazz.snapshot
copylib jazz.splash
copylib jazz.time
copylib jazz.version
copylib jazz.zlib
copylib jiri
copylib scheme
copylib srfi-19
copylib together.launch
copylib update
jas init -open
jas add .
mv .jas Contents/Resources
cd ..

# Sign
/usr/bin/xattr -r -c -s $APP.app
/usr/bin/codesign --force --options runtime --entitlements Entitlements.plist --timestamp --verbose=4 -s "Developer ID Application: Guillaume Cartier (R74FF3EJWG)" $APP.app
