#! /bin/sh

TOGETHER=~/Devel/together
INSTALL=$TOGETHER/install
NOTARY=$TOGETHER/notary

if [ -f ".jaz" ]; then
  . "$(pwd)/.jaz"
else
  echo ".jaz not found"
  exit 1
fi

if [ -z "$JAZCONF" ]; then
  echo "JAZCONF not set"
  exit 1
else
  ENVIRONMENT="$JAZCONF"
fi

if [[ "$(arch)" == "arm64" ]]; then
  APP=together-$ENVIRONMENT-silicon
else
  APP=together-$ENVIRONMENT-mac
fi

# Bail out
set -e

# Staple
cd $NOTARY
xcrun stapler staple -v $APP.app
